services:
  # Primo servizio
  bwlab_doctrine_log.event_listener.logger:
    class: Bwlab\DoctrineLogBundle\EventListener\Logger
    tags:
      - { name: doctrine.event_listener, event: postPersist, priority: 1 }
      - { name: doctrine.event_listener, event: postUpdate, priority: 1 }
      - { name: doctrine.event_listener, event: postFlush, priority: 1 }
      - { name: doctrine.event_listener, event: postRemove, priority: 1 }
      - { name: doctrine.event_listener, event: preRemove, priority: 1 }
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@serializer"
      - "@monolog.logger"
      - "@bwlab_doctrine_log.service.annotation_reader"
      - "%bwlab_doctrine_log.entity_log_class%"

#   Secondo servizio
  bwlab_doctrine_log.service.annotation_reader:
    class: Bwlab\DoctrineLogBundle\Service\AnnotationReader
